//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Thuoc
    {
        public int Id { get; set; }
        public string Madanhmuc { get; set; }
        public string Tenthuoc { get; set; }
        public string Mathuoc { get; set; }
    }
}
