//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Medicine
    {
        public int Id { get; set; }
        public string Mathuoc { get; set; }
        public string Tenthuoc { get; set; }
        public Nullable<double> Soluong { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
        public Nullable<decimal> Gianhap { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string Addwho { get; set; }
    }
}
