//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int Id { get; set; }
        public string Hovaten { get; set; }
        public string Diachi { get; set; }
        public Nullable<long> Sodienthoai { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
    }
}
